# Generated by Django 4.0.3 on 2022-03-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justkidding', '0002_shop_delete_geograph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
