# Generated by Django 4.0.3 on 2022-03-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justkidding', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='Point',
            new_name='Pointlocation',
        ),
    ]
