# Generated by Django 4.0.3 on 2022-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justkidding', '0005_rename_point_distance_pointlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
